name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.minigames.MiniGamesPlugin
description: 'Плагин для управления мини-играми и проведения турниров на сервере ITMOcraft miniGAMES'
authors: [ 'EnderDissa', 's4dnex' ]
contributors: [ 'SumrakBro','acrighthere','Stunnerer' ]
website: ${WEBSITE}

depend: [ ]
softdepend: [ 'LibreLogin', 'voicechat', 'PlaceholderAPI' ]
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}'